### ISSUE TITLE
无法生成图片

### ISSUE THREAD

**Issue by orangegnar** [ldcivan/bf_info_plugin#2]
[MiaoYz][01:03:05.155][ERRO] [bf_info][bf_base]
[MiaoYz][01:03:05.156][ERRO] TypeError: forwardMsg.data.replace is not a function
    at example.makeForwardMsg (file:///F:/yunzai/Yunzai-Bot/plugins/example/bf_info.js:422:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async example.bf_base (file:///F:/yunzai/Yunzai-Bot/plugins/example/bf_info.js:144:26)
    at async PluginsLoader.deal (file:///F:/yunzai/Yunzai-Bot/lib/plugins/loader.js:291:54)

**Comment by YujioNako** [comment]
在某些情况下需要先将object转成string才可调用replace方法，现在已经修复，请更新
另外，本程序返回的不是图片而是一个聊天记录形式的信息
如仍有问题请联系我，否则请关闭该issue

**Comment by orangegnar** [comment]
已解决，感谢大佬
